import urllib.request
import json
import sys

SUPABASE_URL = "https://snvgarluywefmlsimikf.supabase.co/rest/v1"
SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNudmdhcmx1eXdlZm1sc2ltaWtmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4ODU5NTM4NywiZXhwIjoyMTA0MTcxMzg3fQ.o9rTQB_rbBYfWAxRf3h1cDA7vKBpCBEXMjAhFrH8U1Y"

HEADERS = {
    "apikey": SERVICE_KEY,
    "Authorization": f"Bearer {SERVICE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "resolution=merge-duplicates,return=representation"
}

def post_records(endpoint, records):
    req = urllib.request.Request(
        f"{SUPABASE_URL}/{endpoint}",
        data=json.dumps(records).encode('utf-8'),
        headers=HEADERS,
        method="POST"
    )
    try:
        res = urllib.request.urlopen(req)
        return json.loads(res.read().decode('utf-8'))
    except urllib.error.HTTPError as e:
        error_msg = e.read().decode('utf-8')
        print(f"Error on {endpoint}: {e.code} - {error_msg}")
        sys.exit(1)

candidates = [
    {
        "id": "TEST-2026-001",
        "full_name": "Test Aarav Sharma",
        "mobile_number": "+91 98101 11001",
        "whatsapp_number": "+91 98101 11001",
        "email": "test.aarav.sharma@example.com",
        "gender": "Male",
        "age": 24,
        "city": "Noida",
        "area": "Sector 62",
        "address": "Flat 204, Sector 62, Noida, Uttar Pradesh",
        "position_applied": "Sales Executive",
        "department": "HR Recruitment",
        "company_id": "comp-1",
        "company_name": "Essential Soul Lifestyle Pvt Ltd",
        "qualification": "B.Com",
        "total_experience": "2 Years",
        "relevant_experience": "2 Years",
        "current_company": "Retail Corp",
        "current_salary": 22000,
        "expected_salary": 28000,
        "notice_period": "Immediate",
        "preferred_location": "Noida",
        "candidate_source": "Meta Ads",
        "assigned_hr": "Nandani",
        "status": "New Lead",
        "remarks": "TEST DATA - Safe to delete",
        "is_active_joining": False,
        "created_at": "2026-09-06T09:15:00Z",
        "last_activity_date": "2026-09-06T09:15:00Z"
    },
    {
        "id": "TEST-2026-002",
        "full_name": "Test Priya Verma",
        "mobile_number": "+91 98101 11002",
        "whatsapp_number": "+91 98101 11002",
        "email": "test.priya.verma@example.com",
        "gender": "Female",
        "age": 22,
        "city": "Delhi",
        "area": "Janakpuri",
        "address": "Block C, Janakpuri, West Delhi",
        "position_applied": "Telecaller",
        "department": "BKD Recruitment",
        "company_id": "comp-2",
        "company_name": "BKD Retail & Lifestyle Pvt Ltd",
        "qualification": "Graduate",
        "total_experience": "1 Year",
        "relevant_experience": "1 Year",
        "current_company": "CallPoint Services",
        "current_salary": 18000,
        "expected_salary": 22000,
        "notice_period": "Immediate",
        "preferred_location": "Delhi",
        "candidate_source": "Apna",
        "assigned_hr": "Shivani",
        "status": "New Lead",
        "remarks": "TEST DATA - Safe to delete",
        "is_active_joining": False,
        "created_at": "2026-09-06T09:30:00Z",
        "last_activity_date": "2026-09-06T09:30:00Z"
    },
    {
        "id": "TEST-2026-003",
        "full_name": "Test Rahul Kumar",
        "mobile_number": "+91 98101 11003",
        "whatsapp_number": "+91 98101 11003",
        "email": "test.rahul.kumar@example.com",
        "gender": "Male",
        "age": 21,
        "city": "Delhi",
        "area": "Uttam Nagar",
        "address": "East Uttam Nagar, Metro Pillar 650, Delhi",
        "position_applied": "Customer Support Executive",
        "department": "HR Recruitment",
        "company_id": "comp-1",
        "company_name": "Essential Soul Lifestyle Pvt Ltd",
        "qualification": "12th Pass",
        "total_experience": "Fresher",
        "relevant_experience": "Fresher",
        "current_company": "N/A",
        "current_salary": 0,
        "expected_salary": 18000,
        "notice_period": "Immediate",
        "preferred_location": "Delhi",
        "candidate_source": "WorkIndia",
        "assigned_hr": "Priyanka",
        "status": "New Lead",
        "remarks": "TEST DATA - Safe to delete",
        "is_active_joining": False,
        "created_at": "2026-09-06T10:00:00Z",
        "last_activity_date": "2026-09-06T10:00:00Z"
    },
    {
        "id": "TEST-2026-004",
        "full_name": "Test Neha Singh",
        "mobile_number": "+91 98101 11004",
        "whatsapp_number": "+91 98101 11004",
        "email": "test.neha.singh@example.com",
        "gender": "Female",
        "age": 25,
        "city": "Gurugram",
        "area": "Cyber City",
        "address": "DLF Phase 2, Gurugram, Haryana",
        "position_applied": "HR Executive",
        "department": "HR Recruitment",
        "company_id": "comp-1",
        "company_name": "Essential Soul Lifestyle Pvt Ltd",
        "qualification": "MBA (HR)",
        "total_experience": "2 Years",
        "relevant_experience": "2 Years",
        "current_company": "Apex Staffing",
        "current_salary": 24000,
        "expected_salary": 30000,
        "notice_period": "15 Days",
        "preferred_location": "Noida / Gurugram",
        "candidate_source": "Naukri",
        "assigned_hr": "Nandani",
        "status": "Interested",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-06T10:15:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-06T08:00:00Z",
        "last_activity_date": "2026-09-06T10:15:00Z"
    },
    {
        "id": "TEST-2026-005",
        "full_name": "Test Aman Gupta",
        "mobile_number": "+91 98101 11005",
        "whatsapp_number": "+91 98101 11005",
        "email": "test.aman.gupta@example.com",
        "gender": "Male",
        "age": 23,
        "city": "Delhi",
        "area": "Pitampura",
        "address": "KP Block, Pitampura, North West Delhi",
        "position_applied": "Sales Executive",
        "department": "BKD Recruitment",
        "company_id": "comp-2",
        "company_name": "BKD Retail & Lifestyle Pvt Ltd",
        "qualification": "BBA",
        "total_experience": "1.5 Years",
        "relevant_experience": "1.5 Years",
        "current_company": "Zenith Retail",
        "current_salary": 20000,
        "expected_salary": 26000,
        "notice_period": "Immediate",
        "preferred_location": "Delhi / Noida",
        "candidate_source": "Indeed",
        "assigned_hr": "Shivani",
        "status": "Connected",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-06T10:30:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-06T08:30:00Z",
        "last_activity_date": "2026-09-06T10:30:00Z"
    },
    {
        "id": "TEST-2026-006",
        "full_name": "Test Pooja Yadav",
        "mobile_number": "+91 98101 11006",
        "whatsapp_number": "+91 98101 11006",
        "email": "test.pooja.yadav@example.com",
        "gender": "Female",
        "age": 22,
        "city": "Delhi",
        "area": "Rohini",
        "address": "Sector 7, Rohini, North Delhi",
        "position_applied": "Telecaller",
        "department": "HR Recruitment",
        "company_id": "comp-1",
        "company_name": "Essential Soul Lifestyle Pvt Ltd",
        "qualification": "B.A.",
        "total_experience": "1 Year",
        "relevant_experience": "1 Year",
        "current_company": "Vibrant BPO",
        "current_salary": 16000,
        "expected_salary": 20000,
        "notice_period": "Immediate",
        "preferred_location": "Delhi",
        "candidate_source": "WhatsApp",
        "assigned_hr": "Priyanka",
        "status": "Interested",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-06T10:45:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-06T09:00:00Z",
        "last_activity_date": "2026-09-06T10:45:00Z"
    },
    {
        "id": "TEST-2026-007",
        "full_name": "Test Rohit Sharma",
        "mobile_number": "+91 98101 11007",
        "whatsapp_number": "+91 98101 11007",
        "email": "test.rohit.sharma@example.com",
        "gender": "Male",
        "age": 28,
        "city": "Delhi",
        "area": "Peeragarhi",
        "address": "Main Rohtak Road, Peeragarhi, Delhi",
        "position_applied": "Team Leader",
        "department": "HR Recruitment",
        "company_id": "comp-1",
        "company_name": "Essential Soul Lifestyle Pvt Ltd",
        "qualification": "MBA",
        "total_experience": "4 Years",
        "relevant_experience": "3 Years",
        "current_company": "Matrix Infoline",
        "current_salary": 32000,
        "expected_salary": 40000,
        "notice_period": "15 Days",
        "preferred_location": "Delhi / Noida",
        "candidate_source": "Naukri",
        "assigned_hr": "Nandani",
        "status": "Follow-up",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-05T11:00:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-05T10:00:00Z",
        "last_activity_date": "2026-09-06T09:00:00Z"
    },
    {
        "id": "TEST-2026-008",
        "full_name": "Test Simran Kaur",
        "mobile_number": "+91 98101 11008",
        "whatsapp_number": "+91 98101 11008",
        "email": "test.simran.kaur@example.com",
        "gender": "Female",
        "age": 23,
        "city": "Delhi",
        "area": "Dwarka",
        "address": "Sector 12, Dwarka, South West Delhi",
        "position_applied": "Telecaller",
        "department": "BKD Recruitment",
        "company_id": "comp-2",
        "company_name": "BKD Retail & Lifestyle Pvt Ltd",
        "qualification": "Graduate",
        "total_experience": "2 Years",
        "relevant_experience": "2 Years",
        "current_company": "DialTech",
        "current_salary": 18000,
        "expected_salary": 24000,
        "notice_period": "Immediate",
        "preferred_location": "Delhi",
        "candidate_source": "Meta Ads",
        "assigned_hr": "Shivani",
        "status": "Follow-up",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-05T14:00:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-05T11:00:00Z",
        "last_activity_date": "2026-09-06T09:30:00Z"
    },
    {
        "id": "TEST-2026-009",
        "full_name": "Test Deepak Kumar",
        "mobile_number": "+91 98101 11009",
        "whatsapp_number": "+91 98101 11009",
        "email": "test.deepak.kumar@example.com",
        "gender": "Male",
        "age": 24,
        "city": "Bahadurgarh",
        "area": "Line Par",
        "address": "Ward 4, Line Par, Bahadurgarh, Haryana",
        "position_applied": "Back Office Executive",
        "department": "HR Recruitment",
        "company_id": "comp-1",
        "company_name": "Essential Soul Lifestyle Pvt Ltd",
        "qualification": "B.Com",
        "total_experience": "1 Year",
        "relevant_experience": "1 Year",
        "current_company": "Swift Logistics",
        "current_salary": 17000,
        "expected_salary": 22000,
        "notice_period": "Immediate",
        "preferred_location": "Delhi / Bahadurgarh",
        "candidate_source": "Apna",
        "assigned_hr": "Priyanka",
        "status": "Follow-up",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-03T11:00:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-03T09:00:00Z",
        "last_activity_date": "2026-09-04T10:00:00Z"
    },
    {
        "id": "TEST-2026-010",
        "full_name": "Test Anjali Verma",
        "mobile_number": "+91 98101 11010",
        "whatsapp_number": "+91 98101 11010",
        "email": "test.anjali.verma@example.com",
        "gender": "Female",
        "age": 24,
        "city": "Ghaziabad",
        "area": "Indirapuram",
        "address": "Ahinsa Khand 2, Indirapuram, Ghaziabad",
        "position_applied": "HR Executive",
        "department": "HR Recruitment",
        "company_id": "comp-1",
        "company_name": "Essential Soul Lifestyle Pvt Ltd",
        "qualification": "MBA (HR)",
        "total_experience": "2 Years",
        "relevant_experience": "1.5 Years",
        "current_company": "TalentHive",
        "current_salary": 22000,
        "expected_salary": 28000,
        "notice_period": "Immediate",
        "preferred_location": "Noida",
        "candidate_source": "Indeed",
        "assigned_hr": "Nandani",
        "status": "Interview Scheduled",
        "interview_date": "2026-09-06",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-04T10:00:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-04T10:00:00Z",
        "last_activity_date": "2026-09-06T09:00:00Z"
    },
    {
        "id": "TEST-2026-011",
        "full_name": "Test Mohit Singh",
        "mobile_number": "+91 98101 11011",
        "whatsapp_number": "+91 98101 11011",
        "email": "test.mohit.singh@example.com",
        "gender": "Male",
        "age": 25,
        "city": "Delhi",
        "area": "Nangloi",
        "address": "Najafgarh Road, Nangloi, Delhi",
        "position_applied": "Sales Executive",
        "department": "BKD Recruitment",
        "company_id": "comp-2",
        "company_name": "BKD Retail & Lifestyle Pvt Ltd",
        "qualification": "Graduate",
        "total_experience": "2.5 Years",
        "relevant_experience": "2 Years",
        "current_company": "City Mart",
        "current_salary": 22000,
        "expected_salary": 27000,
        "notice_period": "Immediate",
        "preferred_location": "Delhi",
        "candidate_source": "Walk-in",
        "assigned_hr": "Shivani",
        "status": "Interview Confirmed",
        "interview_date": "2026-09-06",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-04T11:00:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-04T11:00:00Z",
        "last_activity_date": "2026-09-06T09:30:00Z"
    },
    {
        "id": "TEST-2026-012",
        "full_name": "Test Riya Sharma",
        "mobile_number": "+91 98101 11012",
        "whatsapp_number": "+91 98101 11012",
        "email": "test.riya.sharma@example.com",
        "gender": "Female",
        "age": 23,
        "city": "Noida",
        "area": "Sector 18",
        "address": "Atta Market, Sector 18, Noida",
        "position_applied": "Digital Marketing Executive",
        "department": "HR Recruitment",
        "company_id": "comp-1",
        "company_name": "Essential Soul Lifestyle Pvt Ltd",
        "qualification": "B.Tech",
        "total_experience": "1.5 Years",
        "relevant_experience": "1.5 Years",
        "current_company": "PixelCraft",
        "current_salary": 25000,
        "expected_salary": 32000,
        "notice_period": "15 Days",
        "preferred_location": "Noida",
        "candidate_source": "Referral",
        "assigned_hr": "Priyanka",
        "status": "Interview Scheduled",
        "interview_date": "2026-09-08",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-05T12:00:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-05T12:00:00Z",
        "last_activity_date": "2026-09-06T10:00:00Z"
    },
    {
        "id": "TEST-2026-013",
        "full_name": "Test Karan Gupta",
        "mobile_number": "+91 98101 11013",
        "whatsapp_number": "+91 98101 11013",
        "email": "test.karan.gupta@example.com",
        "gender": "Male",
        "age": 22,
        "city": "Delhi",
        "area": "Janakpuri",
        "address": "District Centre, Janakpuri, New Delhi",
        "position_applied": "Telecaller",
        "department": "BKD Recruitment",
        "company_id": "comp-2",
        "company_name": "BKD Retail & Lifestyle Pvt Ltd",
        "qualification": "12th Pass",
        "total_experience": "1 Year",
        "relevant_experience": "1 Year",
        "current_company": "ConnectPlus",
        "current_salary": 16000,
        "expected_salary": 20000,
        "notice_period": "Immediate",
        "preferred_location": "Delhi",
        "candidate_source": "Apna",
        "assigned_hr": "Shivani",
        "status": "Interview Confirmed",
        "interview_date": "2026-09-06",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-05T14:00:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-05T14:00:00Z",
        "last_activity_date": "2026-09-06T10:15:00Z"
    },
    {
        "id": "TEST-2026-014",
        "full_name": "Test Sneha Kapoor",
        "mobile_number": "+91 98101 11014",
        "whatsapp_number": "+91 98101 11014",
        "email": "test.sneha.kapoor@example.com",
        "gender": "Female",
        "age": 26,
        "city": "Delhi",
        "area": "Pitampura",
        "address": "Netaji Subhash Place, Pitampura, Delhi",
        "position_applied": "Sales Executive",
        "department": "HR Recruitment",
        "company_id": "comp-1",
        "company_name": "Essential Soul Lifestyle Pvt Ltd",
        "qualification": "B.Com",
        "total_experience": "3 Years",
        "relevant_experience": "2.5 Years",
        "current_company": "Prime Trends",
        "current_salary": 26000,
        "expected_salary": 32000,
        "notice_period": "Immediate",
        "preferred_location": "Delhi / Noida",
        "candidate_source": "Naukri",
        "assigned_hr": "Nandani",
        "status": "Interview Conducted",
        "interview_date": "2026-09-06",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-04T09:00:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-04T09:00:00Z",
        "last_activity_date": "2026-09-06T11:00:00Z"
    },
    {
        "id": "TEST-2026-015",
        "full_name": "Test Vishal Yadav",
        "mobile_number": "+91 98101 11015",
        "whatsapp_number": "+91 98101 11015",
        "email": "test.vishal.yadav@example.com",
        "gender": "Male",
        "age": 23,
        "city": "Delhi",
        "area": "Uttam Nagar",
        "address": "Near Metro Station, Uttam Nagar, Delhi",
        "position_applied": "Telecaller",
        "department": "BKD Recruitment",
        "company_id": "comp-2",
        "company_name": "BKD Retail & Lifestyle Pvt Ltd",
        "qualification": "B.A.",
        "total_experience": "1.5 Years",
        "relevant_experience": "1.5 Years",
        "current_company": "TeleMax Solutions",
        "current_salary": 17000,
        "expected_salary": 21000,
        "notice_period": "Immediate",
        "preferred_location": "Delhi",
        "candidate_source": "WorkIndia",
        "assigned_hr": "Shivani",
        "status": "Interview Conducted",
        "interview_date": "2026-09-06",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-04T12:00:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-04T12:00:00Z",
        "last_activity_date": "2026-09-06T11:45:00Z"
    },
    {
        "id": "TEST-2026-016",
        "full_name": "Test Komal Singh",
        "mobile_number": "+91 98101 11016",
        "whatsapp_number": "+91 98101 11016",
        "email": "test.komal.singh@example.com",
        "gender": "Female",
        "age": 25,
        "city": "Noida",
        "area": "Sector 62",
        "address": "Tower 3, Sector 62, Noida",
        "position_applied": "HR Executive",
        "department": "HR Recruitment",
        "company_id": "comp-1",
        "company_name": "Essential Soul Lifestyle Pvt Ltd",
        "qualification": "MBA (HR)",
        "total_experience": "2 Years",
        "relevant_experience": "2 Years",
        "current_company": "ProPeople",
        "current_salary": 24000,
        "expected_salary": 30000,
        "salary_offered": 28000,
        "notice_period": "Immediate",
        "preferred_location": "Noida",
        "candidate_source": "Indeed",
        "assigned_hr": "Nandani",
        "status": "Selected",
        "interview_date": "2026-09-05",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-03T09:00:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-03T09:00:00Z",
        "last_activity_date": "2026-09-06T12:00:00Z"
    },
    {
        "id": "TEST-2026-017",
        "full_name": "Test Akash Verma",
        "mobile_number": "+91 98101 11017",
        "whatsapp_number": "+91 98101 11017",
        "email": "test.akash.verma@example.com",
        "gender": "Male",
        "age": 24,
        "city": "Delhi",
        "area": "Dwarka",
        "address": "Sector 10, Dwarka, Delhi",
        "position_applied": "Sales Executive",
        "department": "BKD Recruitment",
        "company_id": "comp-2",
        "company_name": "BKD Retail & Lifestyle Pvt Ltd",
        "qualification": "Graduate",
        "total_experience": "2 Years",
        "relevant_experience": "2 Years",
        "current_company": "Lifestyle Hub",
        "current_salary": 21000,
        "expected_salary": 26000,
        "salary_offered": 25000,
        "notice_period": "Immediate",
        "preferred_location": "Delhi / Noida",
        "candidate_source": "Meta Ads",
        "assigned_hr": "Priyanka",
        "status": "Selected",
        "interview_date": "2026-09-05",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-03T10:00:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-03T10:00:00Z",
        "last_activity_date": "2026-09-06T12:30:00Z"
    },
    {
        "id": "TEST-2026-018",
        "full_name": "Test Nisha Gupta",
        "mobile_number": "+91 98101 11018",
        "whatsapp_number": "+91 98101 11018",
        "email": "test.nisha.gupta@example.com",
        "gender": "Female",
        "age": 22,
        "city": "Delhi",
        "area": "Rohini",
        "address": "Sector 11, Rohini, Delhi",
        "position_applied": "Telecaller",
        "department": "BKD Recruitment",
        "company_id": "comp-2",
        "company_name": "BKD Retail & Lifestyle Pvt Ltd",
        "qualification": "12th Pass",
        "total_experience": "1 Year",
        "relevant_experience": "1 Year",
        "current_company": "QuickCall",
        "current_salary": 16000,
        "expected_salary": 20000,
        "salary_offered": 20000,
        "joining_date": "2026-09-06",
        "notice_period": "Immediate",
        "preferred_location": "Delhi",
        "candidate_source": "Apna",
        "assigned_hr": "Shivani",
        "status": "Joined",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-01T09:00:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-01T09:00:00Z",
        "last_activity_date": "2026-09-06T09:30:00Z"
    },
    {
        "id": "TEST-2026-019",
        "full_name": "Test Manish Kumar",
        "mobile_number": "+91 98101 11019",
        "whatsapp_number": "+91 98101 11019",
        "email": "test.manish.kumar@example.com",
        "gender": "Male",
        "age": 26,
        "city": "Ghaziabad",
        "area": "Vaishali",
        "address": "Sector 4, Vaishali, Ghaziabad",
        "position_applied": "Back Office Executive",
        "department": "HR Recruitment",
        "company_id": "comp-1",
        "company_name": "Essential Soul Lifestyle Pvt Ltd",
        "qualification": "Graduate",
        "total_experience": "2.5 Years",
        "relevant_experience": "2 Years",
        "current_company": "Alpha Ops",
        "current_salary": 20000,
        "expected_salary": 25000,
        "salary_offered": 24000,
        "joining_date": "2026-08-30",
        "active_joining_date": "2026-09-06",
        "is_active_joining": True,
        "notice_period": "Immediate",
        "preferred_location": "Noida / Ghaziabad",
        "candidate_source": "Naukri",
        "assigned_hr": "Nandani",
        "status": "Active Joining",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-08-20T10:00:00Z",
        "created_at": "2026-08-20T10:00:00Z",
        "last_activity_date": "2026-09-06T10:00:00Z"
    },
    {
        "id": "TEST-2026-020",
        "full_name": "Test Sakshi Sharma",
        "mobile_number": "+91 98101 11020",
        "whatsapp_number": "+91 98101 11020",
        "email": "test.sakshi.sharma@example.com",
        "gender": "Female",
        "age": 23,
        "city": "Delhi",
        "area": "Peeragarhi",
        "address": "Udyog Nagar Metro, Peeragarhi, Delhi",
        "position_applied": "Customer Support Executive",
        "department": "HR Recruitment",
        "company_id": "comp-1",
        "company_name": "Essential Soul Lifestyle Pvt Ltd",
        "qualification": "Graduate",
        "total_experience": "1 Year",
        "relevant_experience": "1 Year",
        "current_company": "ZenDesk Care",
        "current_salary": 17000,
        "expected_salary": 21000,
        "notice_period": "Immediate",
        "preferred_location": "Delhi",
        "candidate_source": "WorkIndia",
        "assigned_hr": "Priyanka",
        "status": "No Show",
        "remarks": "TEST DATA - Safe to delete",
        "first_call_date": "2026-09-02T10:00:00Z",
        "is_active_joining": False,
        "created_at": "2026-09-02T10:00:00Z",
        "last_activity_date": "2026-09-05T15:00:00Z"
    }
]

follow_ups = [
    {
        "id": "test-fu-001",
        "candidate_id": "TEST-2026-007",
        "scheduled_date": "2026-09-06",
        "scheduled_time": "11:30",
        "type": "Call",
        "notes": "Candidate asked to call back in afternoon after 2 PM to finalize interview slot.",
        "completed": False,
        "conducted_by": "Nandani",
        "outcome": "Interested",
        "next_follow_up_date": "2026-09-06",
        "created_at": "2026-09-05T11:00:00Z"
    },
    {
        "id": "test-fu-002",
        "candidate_id": "TEST-2026-008",
        "scheduled_date": "2026-09-06",
        "scheduled_time": "14:00",
        "type": "Call",
        "notes": "Interested in Telecaller role, needs salary confirmation before scheduling.",
        "completed": False,
        "conducted_by": "Shivani",
        "outcome": "Follow-up",
        "next_follow_up_date": "2026-09-06",
        "created_at": "2026-09-05T14:00:00Z"
    },
    {
        "id": "test-fu-003",
        "candidate_id": "TEST-2026-009",
        "scheduled_date": "2026-09-04",
        "scheduled_time": "10:00",
        "type": "Call",
        "notes": "Phone was busy on first attempt; reschedule touchpoint.",
        "completed": False,
        "conducted_by": "Priyanka",
        "outcome": "Follow-up",
        "next_follow_up_date": "2026-09-06",
        "created_at": "2026-09-03T11:00:00Z"
    },
    {
        "id": "test-fu-004",
        "candidate_id": "TEST-2026-008",
        "scheduled_date": "2026-09-08",
        "scheduled_time": "15:00",
        "type": "WhatsApp",
        "notes": "Scheduled upcoming WhatsApp check-in for document submission.",
        "completed": False,
        "conducted_by": "Shivani",
        "outcome": "Follow-up",
        "next_follow_up_date": "2026-09-08",
        "created_at": "2026-09-06T09:00:00Z"
    }
]

interviews = [
    {
        "id": "test-int-001",
        "candidate_id": "TEST-2026-010",
        "candidate_name": "Test Anjali Verma",
        "candidate_phone": "+91 98101 11010",
        "candidate_role": "HR Executive",
        "scheduled_date": "2026-09-06",
        "scheduled_time": "11:00",
        "round": "Initial Round",
        "interviewer_name": "Vikram Singh",
        "interviewer_role": "Interviewer",
        "status": "Scheduled",
        "attendance_status": "Scheduled",
        "evaluation": None,
        "notes": "Office interview at Sector 62, Noida. Candidate confirmed arrival.",
        "created_at": "2026-09-04T10:00:00Z"
    },
    {
        "id": "test-int-002",
        "candidate_id": "TEST-2026-011",
        "candidate_name": "Test Mohit Singh",
        "candidate_phone": "+91 98101 11011",
        "candidate_role": "Sales Executive",
        "scheduled_date": "2026-09-06",
        "scheduled_time": "12:30",
        "round": "Store Round",
        "interviewer_name": "Rajesh Khanna",
        "interviewer_role": "Interviewer",
        "status": "Confirmed",
        "attendance_status": "Confirmed",
        "evaluation": None,
        "notes": "In-person interview at B-12 Sector 63, Noida. Candidate re-confirmed on morning call.",
        "created_at": "2026-09-04T11:00:00Z"
    },
    {
        "id": "test-int-003",
        "candidate_id": "TEST-2026-012",
        "candidate_name": "Test Riya Sharma",
        "candidate_phone": "+91 98101 11012",
        "candidate_role": "Digital Marketing Executive",
        "scheduled_date": "2026-09-08",
        "scheduled_time": "14:00",
        "round": "Technical Round",
        "interviewer_name": "Aditya Mathur",
        "interviewer_role": "Director",
        "status": "Scheduled",
        "attendance_status": "Scheduled",
        "evaluation": None,
        "notes": "Video interview scheduled via Google Meet.",
        "created_at": "2026-09-05T12:00:00Z"
    },
    {
        "id": "test-int-004",
        "candidate_id": "TEST-2026-013",
        "candidate_name": "Test Karan Gupta",
        "candidate_phone": "+91 98101 11013",
        "candidate_role": "Telecaller",
        "scheduled_date": "2026-09-06",
        "scheduled_time": "15:00",
        "round": "Calling Screening",
        "interviewer_name": "Pooja Verma",
        "interviewer_role": "Managing Head",
        "status": "Confirmed",
        "attendance_status": "Confirmed",
        "evaluation": None,
        "notes": "Telephonic communication and vocal screening interview.",
        "created_at": "2026-09-05T14:00:00Z"
    },
    {
        "id": "test-int-005",
        "candidate_id": "TEST-2026-014",
        "candidate_name": "Test Sneha Kapoor",
        "candidate_phone": "+91 98101 11014",
        "candidate_role": "Sales Executive",
        "scheduled_date": "2026-09-06",
        "scheduled_time": "10:30",
        "round": "Final Round",
        "interviewer_name": "Vikram Singh",
        "interviewer_role": "Interviewer",
        "status": "Conducted",
        "attendance_status": "Conducted",
        "evaluation": {
            "communication": 4,
            "confidence": 4,
            "experience": 3,
            "jobKnowledge": 4,
            "stability": 4,
            "salaryFit": 4,
            "attitude": 5,
            "overallSuitability": 4,
            "averageRating": 4.0,
            "finalResult": "Selected",
            "interviewerRemarks": "Strong candidate with clear product pitch presentation. Recommended for offer release.",
            "evaluatedAt": "2026-09-06T11:00:00Z"
        },
        "notes": "Interview completed successfully; candidate demonstrated great retail and floor sales aptitude.",
        "created_at": "2026-09-04T09:00:00Z"
    },
    {
        "id": "test-int-006",
        "candidate_id": "TEST-2026-015",
        "candidate_name": "Test Vishal Yadav",
        "candidate_phone": "+91 98101 11015",
        "candidate_role": "Telecaller",
        "scheduled_date": "2026-09-06",
        "scheduled_time": "11:30",
        "round": "Floor Assessment",
        "interviewer_name": "Rahul Deshmukh",
        "interviewer_role": "Interviewer",
        "status": "Conducted",
        "attendance_status": "Conducted",
        "evaluation": {
            "communication": 4,
            "confidence": 3,
            "experience": 3,
            "jobKnowledge": 3,
            "stability": 3,
            "salaryFit": 4,
            "attitude": 4,
            "overallSuitability": 3.5,
            "averageRating": 3.5,
            "finalResult": "Salary Discussion",
            "interviewerRemarks": "Good dialect and vocal clarity. Fits budget, slight negotiation needed.",
            "evaluatedAt": "2026-09-06T11:45:00Z"
        },
        "notes": "Conducted assessment. Good fit for voice process.",
        "created_at": "2026-09-04T12:00:00Z"
    },
    {
        "id": "test-int-007",
        "candidate_id": "TEST-2026-016",
        "candidate_name": "Test Komal Singh",
        "candidate_phone": "+91 98101 11016",
        "candidate_role": "HR Executive",
        "scheduled_date": "2026-09-05",
        "scheduled_time": "14:00",
        "round": "Final Round",
        "interviewer_name": "Vikram Singh",
        "interviewer_role": "Interviewer",
        "status": "Conducted",
        "attendance_status": "Conducted",
        "evaluation": {
            "communication": 5,
            "confidence": 4,
            "experience": 4,
            "jobKnowledge": 4,
            "stability": 4,
            "salaryFit": 4,
            "attitude": 5,
            "overallSuitability": 4.5,
            "averageRating": 4.2,
            "finalResult": "Selected",
            "interviewerRemarks": "Excellent HR lifecycle domain knowledge. Selected for offer.",
            "evaluatedAt": "2026-09-05T15:00:00Z"
        },
        "notes": "Selected candidate.",
        "created_at": "2026-09-03T09:00:00Z"
    },
    {
        "id": "test-int-008",
        "candidate_id": "TEST-2026-017",
        "candidate_name": "Test Akash Verma",
        "candidate_phone": "+91 98101 11017",
        "candidate_role": "Sales Executive",
        "scheduled_date": "2026-09-05",
        "scheduled_time": "16:00",
        "round": "Final Round",
        "interviewer_name": "Rajesh Khanna",
        "interviewer_role": "Interviewer",
        "status": "Conducted",
        "attendance_status": "Conducted",
        "evaluation": {
            "communication": 4,
            "confidence": 4,
            "experience": 4,
            "jobKnowledge": 4,
            "stability": 4,
            "salaryFit": 4,
            "attitude": 4,
            "overallSuitability": 4.0,
            "averageRating": 4.0,
            "finalResult": "Selected",
            "interviewerRemarks": "Strong retail sales flair, selected for BKD team.",
            "evaluatedAt": "2026-09-05T17:00:00Z"
        },
        "notes": "Selected candidate.",
        "created_at": "2026-09-03T10:00:00Z"
    },
    {
        "id": "test-int-009",
        "candidate_id": "TEST-2026-020",
        "candidate_name": "Test Sakshi Sharma",
        "candidate_phone": "+91 98101 11020",
        "candidate_role": "Customer Support Executive",
        "scheduled_date": "2026-09-05",
        "scheduled_time": "14:30",
        "round": "Initial Screening",
        "interviewer_name": "Vikram Singh",
        "interviewer_role": "Interviewer",
        "status": "No Show",
        "attendance_status": "No Show",
        "evaluation": None,
        "notes": "Candidate did not attend scheduled interview; phone switched off on follow-up.",
        "created_at": "2026-09-02T10:00:00Z"
    }
]

def normalize_records(records):
    all_keys = set()
    for r in records:
        all_keys.update(r.keys())
    return [{k: r.get(k, None) for k in all_keys} for r in records]

print("1. Upserting 20 candidates into Supabase...")
cand_res = post_records("candidates", normalize_records(candidates))
print(f"Successfully upserted {len(cand_res)} candidate records into Supabase!")

print("2. Upserting 4 follow-up records into Supabase...")
fu_res = post_records("follow_ups", normalize_records(follow_ups))
print(f"Successfully upserted {len(fu_res)} follow-up records into Supabase!")

print("3. Upserting 9 interview records into Supabase...")
int_res = post_records("interviews", normalize_records(interviews))
print(f"Successfully upserted {len(int_res)} interview records into Supabase!")

print("ALL DUMMY TEST DATA SUCCESSFULLY INSERTED INTO SUPABASE!")
