import { 
  Candidate, 
  FollowUpRecord, 
  InterviewRecord, 
  JobOpening, 
  SourceAdSpend, 
  SystemSettings, 
  UserProfile, 
  AuditLogEntry, 
  TrainingRecord,
  Company,
  DepartmentItem,
  TargetSetting,
  RolePermissionsMap,
  TermsClause,
  OfferLetter
} from './types';

export const INITIAL_COMPANIES: Company[] = [
  {
    "id": "comp-1",
    "name": "Essential Soul Lifestyle Pvt Ltd",
    "code": "ESL",
    "legalName": "Essential Soul Lifestyle Private Limited",
    "cin": "U74999UP2022PTC168921",
    "gstin": "09AAECE1234F1Z5",
    "address": "Plot A-40, ITHUM Tower, Block A, Sector 62",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "pincode": "201309",
    "email": "info@essentialsoul.com",
    "phone": "+91 98765 43210",
    "website": "https://essentialsoul.com",
    "departments": [
      "HR Recruitment",
      "Management",
      "Digital Marketing"
    ],
    "isActive": true,
    "createdAt": "2024-01-15T09:00:00Z",
    "adminUserId": "esl.admin",
    "adminPassword": "ESL@Corp2026",
    "masterContactPerson": "Aditya Mathur (Director)",
    "lastPasswordChanged": "2026-09-01T09:00:00Z"
  },
  {
    "id": "comp-2",
    "name": "BKD Retail & Lifestyle Pvt Ltd",
    "code": "BKD",
    "legalName": "BKD Lifestyle & Retail Private Limited",
    "cin": "U52100DL2023PTC189432",
    "gstin": "07AABCB9876K1Z2",
    "address": "B-12, Sector 63, Near Electronic City Metro",
    "city": "Noida",
    "state": "Uttar Pradesh",
    "pincode": "201301",
    "email": "careers@bkdlifestyle.com",
    "phone": "+91 98111 22334",
    "website": "https://bkdlifestyle.com",
    "departments": [
      "BKD Recruitment",
      "Retail Store Operations",
      "Calling Center"
    ],
    "isActive": true,
    "createdAt": "2024-06-01T10:00:00Z",
    "adminUserId": "bkd.admin",
    "adminPassword": "BKD@Corp2026",
    "masterContactPerson": "Pooja Verma (Managing Head)",
    "lastPasswordChanged": "2026-09-01T09:00:00Z"
  },
  {
    "id": "comp-3",
    "name": "Soul Organic Wellness LLP",
    "code": "SOW",
    "legalName": "Soul Organic Wellness Limited Liability Partnership",
    "cin": "AAY-9821",
    "gstin": "09AAHCS4321E1Z9",
    "address": "C-24, Okhla Phase 3, Industrial Area",
    "city": "New Delhi",
    "state": "Delhi",
    "pincode": "110020",
    "email": "hr@soulorganic.in",
    "phone": "+91 98999 55443",
    "website": "https://soulorganic.in",
    "departments": [
      "Wellness Operations",
      "Customer Care"
    ],
    "isActive": true,
    "createdAt": "2025-02-10T11:00:00Z",
    "adminUserId": "sow.admin",
    "adminPassword": "SOW@Corp2026",
    "masterContactPerson": "Sunita Yadav (Partner)",
    "lastPasswordChanged": "2026-09-01T09:00:00Z"
  }
];

export const INITIAL_DEPARTMENTS: DepartmentItem[] = [
  {
    id: 'dept-1',
    name: 'HR Recruitment',
    code: 'HR-REC',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    headName: 'Nandani',
    headEmail: 'nandani.hr@essentialsoul.com',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 20,
    description: 'Corporate HR talent acquisition team responsible for core office and sales staffing.',
    isActive: true,
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'dept-2',
    name: 'BKD Recruitment',
    code: 'BKD-REC',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    headName: 'Shivani',
    headEmail: 'shivani.bkd@essentialsoul.com',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 20,
    description: 'Outbound telecalling, retail, and field recruitment team for BKD subsidiaries.',
    isActive: true,
    createdAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'dept-3',
    name: 'Management',
    code: 'MGMT',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    headName: 'Aditya Mathur',
    headEmail: 'aditya.management@essentialsoul.com',
    dailyInterviewTarget: 0,
    monthlyActiveJoiningTarget: 0,
    description: 'Executive management, leadership oversight, strategic target monitoring.',
    isActive: true,
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'dept-4',
    name: 'Retail Store Operations',
    code: 'RTL-OPS',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    headName: 'Vikram Singh',
    headEmail: 'vikram.interviewer@essentialsoul.com',
    dailyInterviewTarget: 3,
    monthlyActiveJoiningTarget: 10,
    description: 'Retail stores, floor supervisors, inventory and showroom attendants.',
    isActive: true,
    createdAt: '2025-01-10T10:00:00Z',
  },
];

export const INITIAL_TARGET_SETTINGS: TargetSetting[] = [
  {
    id: 'tgt-1',
    targetType: 'Company',
    targetEntityId: 'comp-1',
    targetEntityName: 'Essential Soul Lifestyle Pvt Ltd',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 15,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-2',
    targetType: 'Company',
    targetEntityId: 'comp-2',
    targetEntityName: 'BKD Retail & Lifestyle Pvt Ltd',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 15,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-3',
    targetType: 'Department',
    targetEntityId: 'dept-1',
    targetEntityName: 'HR Recruitment (Nandani)',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 15,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-4',
    targetType: 'Department',
    targetEntityId: 'dept-1',
    targetEntityName: 'HR Recruitment (Nandani)',
    period: 'Daily',
    metric: 'Interviews Conducted',
    targetValue: 5,
    minimumBenchmark: 3,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-5',
    targetType: 'Department',
    targetEntityId: 'dept-2',
    targetEntityName: 'BKD Recruitment (Shivani)',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 15,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-6',
    targetType: 'Department',
    targetEntityId: 'dept-2',
    targetEntityName: 'BKD Recruitment (Shivani)',
    period: 'Daily',
    metric: 'Interviews Conducted',
    targetValue: 5,
    minimumBenchmark: 3,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-7',
    targetType: 'HR Executive',
    targetEntityId: 'usr-1',
    targetEntityName: 'Nandani',
    period: 'Daily',
    metric: 'Interviews Conducted',
    targetValue: 5,
    minimumBenchmark: 4,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-8',
    targetType: 'HR Executive',
    targetEntityId: 'usr-1',
    targetEntityName: 'Nandani',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 16,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-9',
    targetType: 'HR Executive',
    targetEntityId: 'usr-2',
    targetEntityName: 'Shivani',
    period: 'Daily',
    metric: 'Interviews Conducted',
    targetValue: 5,
    minimumBenchmark: 4,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-10',
    targetType: 'HR Executive',
    targetEntityId: 'usr-2',
    targetEntityName: 'Shivani',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 16,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'usr-1',
    name: 'Nandani Sharma',
    email: 'nandani.hr@essentialsoul.com',
    phone: '+91 98765 00001',
    userId: 'nandani.hr',
    password: 'Nandani@2026',
    role: 'HR Head',
    department: 'HR Recruitment',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 20,
    status: 'Active',
    createdAt: '2024-01-15T09:00:00Z',
    lastPasswordChanged: '2026-08-15T10:30:00Z',
  },
  {
    id: 'usr-2',
    name: 'Shivani Rajput',
    email: 'shivani.bkd@essentialsoul.com',
    phone: '+91 98765 00002',
    userId: 'shivani.bkd',
    password: 'Shivani@2026',
    role: 'HR Executive',
    department: 'BKD Recruitment',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 20,
    status: 'Active',
    createdAt: '2024-06-01T10:00:00Z',
    lastPasswordChanged: '2026-08-20T11:15:00Z',
  },
  {
    id: 'usr-3',
    name: 'Aditya Mathur',
    email: 'aditya.management@essentialsoul.com',
    phone: '+91 98765 00000',
    userId: 'aditya.mathur',
    password: 'Aditya@2026',
    role: 'Director / Management',
    department: 'Management',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 0,
    monthlyActiveJoiningTarget: 0,
    status: 'Active',
    createdAt: '2024-01-15T09:00:00Z',
    lastPasswordChanged: '2026-09-01T09:00:00Z',
  },
  {
    id: 'usr-4',
    name: 'Super Admin',
    email: 'admin@essentialsoul.com',
    phone: '+91 98765 00003',
    userId: 'admin',
    password: 'Admin@2026',
    role: 'Super Admin',
    department: 'Management',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 0,
    monthlyActiveJoiningTarget: 0,
    status: 'Active',
    createdAt: '2024-01-15T09:00:00Z',
    lastPasswordChanged: '2026-09-01T08:00:00Z',
  },
  {
    id: 'usr-5',
    name: 'Vikram Singh',
    email: 'vikram.interviewer@essentialsoul.com',
    phone: '+91 98765 00004',
    userId: 'vikram.singh',
    password: 'Vikram@2026',
    role: 'Interviewer',
    department: 'HR Recruitment',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 4,
    monthlyActiveJoiningTarget: 12,
    status: 'Active',
    createdAt: '2024-03-10T11:00:00Z',
    lastPasswordChanged: '2026-08-10T14:20:00Z',
  },
  {
    id: 'usr-6',
    name: 'Pooja Verma',
    email: 'pooja.verma@bkdlifestyle.com',
    phone: '+91 98111 22334',
    userId: 'pooja.verma',
    password: 'Pooja@2026',
    role: 'HR Head',
    department: 'BKD Recruitment',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 20,
    status: 'Active',
    createdAt: '2024-06-01T10:00:00Z',
    lastPasswordChanged: '2026-08-25T11:00:00Z',
  },
  {
    id: 'usr-7',
    name: 'Rajesh Khanna',
    email: 'rajesh.khanna@bkdlifestyle.com',
    phone: '+91 98111 22335',
    userId: 'rajesh.tl',
    password: 'Rajesh@2026',
    role: 'Team Leader',
    department: 'Retail Store Operations',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    dailyInterviewTarget: 3,
    monthlyActiveJoiningTarget: 10,
    status: 'Active',
    createdAt: '2024-07-15T09:30:00Z',
    lastPasswordChanged: '2026-08-20T10:00:00Z',
  },
  {
    id: 'usr-8',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@essentialsoul.com',
    phone: '+91 98765 00005',
    userId: 'ananya.rec',
    password: 'Ananya@2026',
    role: 'Recruiter',
    department: 'HR Recruitment',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 4,
    monthlyActiveJoiningTarget: 15,
    status: 'Active',
    createdAt: '2024-08-01T10:00:00Z',
    lastPasswordChanged: '2026-08-18T12:00:00Z',
  },
  {
    id: 'usr-9',
    name: 'Kunal Malhotra',
    email: 'kunal.malhotra@essentialsoul.com',
    phone: '+91 98765 00006',
    userId: 'kunal.inv',
    password: 'Kunal@2026',
    role: 'Interviewer',
    department: 'Management',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 4,
    monthlyActiveJoiningTarget: 10,
    status: 'Active',
    createdAt: '2024-08-15T11:00:00Z',
    lastPasswordChanged: '2026-08-22T14:00:00Z',
  },
  {
    id: 'usr-10',
    name: 'Priya Sharma',
    email: 'priya.sharma@bkdlifestyle.com',
    phone: '+91 98111 22336',
    userId: 'priya.exec',
    password: 'Priya@2026',
    role: 'HR Executive',
    department: 'Calling Center',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 18,
    status: 'Active',
    createdAt: '2024-09-01T09:00:00Z',
    lastPasswordChanged: '2026-08-25T15:00:00Z',
  },
  {
    id: 'usr-11',
    name: 'Amit Patel',
    email: 'amit.patel@bkdlifestyle.com',
    phone: '+91 98111 22337',
    userId: 'amit.tl',
    password: 'Amit@2026',
    role: 'Team Leader',
    department: 'Calling Center',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    dailyInterviewTarget: 3,
    monthlyActiveJoiningTarget: 12,
    status: 'Active',
    createdAt: '2024-09-10T10:00:00Z',
    lastPasswordChanged: '2026-08-20T16:00:00Z',
  },
  {
    id: 'usr-12',
    name: 'Neha Gupta',
    email: 'neha.gupta@soulorganic.in',
    phone: '+91 98999 55444',
    userId: 'neha.rec',
    password: 'Neha@2026',
    role: 'Recruiter',
    department: 'Wellness Operations',
    companyId: 'comp-3',
    companyName: 'Soul Organic Wellness LLP',
    dailyInterviewTarget: 4,
    monthlyActiveJoiningTarget: 15,
    status: 'Active',
    createdAt: '2025-02-15T09:00:00Z',
    lastPasswordChanged: '2026-08-15T09:30:00Z',
  },
  {
    id: 'usr-13',
    name: 'Rahul Deshmukh',
    email: 'rahul.deshmukh@bkdlifestyle.com',
    phone: '+91 98111 22338',
    userId: 'rahul.inv',
    password: 'Rahul@2026',
    role: 'Interviewer',
    department: 'BKD Recruitment',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    dailyInterviewTarget: 4,
    monthlyActiveJoiningTarget: 12,
    status: 'Active',
    createdAt: '2024-10-01T10:30:00Z',
    lastPasswordChanged: '2026-08-19T11:00:00Z',
  },
  {
    id: 'usr-14',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@soulorganic.in',
    phone: '+91 98999 55445',
    userId: 'sneha.exec',
    password: 'Sneha@2026',
    role: 'HR Executive',
    department: 'Wellness Operations',
    companyId: 'comp-3',
    companyName: 'Soul Organic Wellness LLP',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 20,
    status: 'Active',
    createdAt: '2025-02-20T10:00:00Z',
    lastPasswordChanged: '2026-08-25T14:30:00Z',
  },
  {
    id: 'usr-15',
    name: 'Deepak Joshi',
    email: 'deepak.joshi@essentialsoul.com',
    phone: '+91 98765 00007',
    userId: 'deepak.rec',
    password: 'Deepak@2026',
    role: 'Recruiter',
    department: 'HR Recruitment',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 4,
    monthlyActiveJoiningTarget: 14,
    status: 'Active',
    createdAt: '2024-11-01T09:00:00Z',
    lastPasswordChanged: '2026-08-28T16:00:00Z',
  },
  {
    id: 'usr-16',
    name: 'Meera Nair',
    email: 'meera.nair@essentialsoul.com',
    phone: '+91 98765 00008',
    userId: 'meera.tl',
    password: 'Meera@2026',
    role: 'Team Leader',
    department: 'HR Recruitment',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 3,
    monthlyActiveJoiningTarget: 15,
    status: 'Active',
    createdAt: '2024-11-15T11:00:00Z',
    lastPasswordChanged: '2026-08-30T10:00:00Z',
  },
  {
    id: 'usr-17',
    name: 'Gaurav Tiwari',
    email: 'gaurav.tiwari@bkdlifestyle.com',
    phone: '+91 98111 22339',
    userId: 'gaurav.inv',
    password: 'Gaurav@2026',
    role: 'Interviewer',
    department: 'Retail Store Operations',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    dailyInterviewTarget: 0,
    monthlyActiveJoiningTarget: 0,
    status: 'Inactive',
    createdAt: '2024-05-10T10:00:00Z',
    lastPasswordChanged: '2026-05-10T10:00:00Z',
  },
  {
    id: 'usr-18',
    name: 'Kavita Saxena',
    email: 'kavita.saxena@bkdlifestyle.com',
    phone: '+91 98111 22340',
    userId: 'kavita.rec',
    password: 'Kavita@2026',
    role: 'Recruiter',
    department: 'BKD Recruitment',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    dailyInterviewTarget: 0,
    monthlyActiveJoiningTarget: 0,
    status: 'Inactive',
    createdAt: '2024-06-15T09:00:00Z',
    lastPasswordChanged: '2026-06-15T09:00:00Z',
  },
  {
    id: 'usr-19',
    name: 'Sanjay Kapoor',
    email: 'sanjay.kapoor@essentialsoul.com',
    phone: '+91 98765 00009',
    userId: 'sanjay.exec',
    password: 'Sanjay@2026',
    role: 'HR Executive',
    department: 'HR Recruitment',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 0,
    monthlyActiveJoiningTarget: 0,
    status: 'Inactive',
    createdAt: '2024-04-01T09:00:00Z',
    lastPasswordChanged: '2024-04-01T09:00:00Z',
  },
  {
    id: 'usr-20',
    name: 'Ritu Choudhary',
    email: 'ritu.choudhary@soulorganic.in',
    phone: '+91 98999 55446',
    userId: 'ritu.rec',
    password: 'Ritu@2026',
    role: 'Recruiter',
    department: 'Customer Care',
    companyId: 'comp-3',
    companyName: 'Soul Organic Wellness LLP',
    dailyInterviewTarget: 4,
    monthlyActiveJoiningTarget: 14,
    status: 'Active',
    createdAt: '2025-03-01T10:00:00Z',
    lastPasswordChanged: '2026-08-20T12:00:00Z',
  },
];

export const DEFAULT_POSITIONS: string[] = [
  'Sales Executive',
  'Telecaller',
  'HR Executive',
  'Team Leader',
  'Digital Marketing Executive',
  'Back Office Executive',
  'Customer Support Executive',
  'Calling Executive',
  'Operations Executive',
];

export const INITIAL_SETTINGS: SystemSettings = {
  activeJoiningDaysThreshold: 7,
  companyName: 'Essential Soul Lifestyle Pvt Ltd',
  companyAddress: 'Sector 62, Noida, Uttar Pradesh, 201309',
  companyPhone: '+91 98765 43210',
};

// Today's date reference
export const TODAY = '2026-09-06';
export const YESTERDAY = '2026-09-05';
export const TWO_DAYS_AGO = '2026-09-04';
export const SEVEN_DAYS_AGO = '2026-08-30';
export const TEN_DAYS_AGO = '2026-08-27';

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    "id": "TEST-2026-001",
    "fullName": "Test Aarav Sharma",
    "mobileNumber": "+91 98101 11001",
    "whatsappNumber": "+91 98101 11001",
    "gender": "Male",
    "age": 24,
    "email": "test.aarav.sharma@example.com",
    "city": "Noida",
    "area": "Sector 62",
    "address": "Flat 204, Sector 62, Noida, Uttar Pradesh",
    "positionApplied": "Sales Executive",
    "department": "HR Recruitment",
    "companyId": "comp-1",
    "companyName": "Essential Soul Lifestyle Pvt Ltd",
    "qualification": "B.Com",
    "totalExperience": "2 Years",
    "relevantExperience": "2 Years",
    "currentCompany": "Retail Corp",
    "currentSalary": 22000,
    "expectedSalary": 28000,
    "noticePeriod": "Immediate",
    "preferredLocation": "Noida",
    "candidateSource": "Meta Ads",
    "assignedHr": "Nandani",
    "status": "New Lead",
    "remarks": "TEST DATA - Safe to delete",
    "isActiveJoining": false,
    "createdAt": "2026-09-06T09:15:00Z",
    "lastActivityDate": "2026-09-06T09:15:00Z"
  },
  {
    "id": "TEST-2026-002",
    "fullName": "Test Priya Verma",
    "mobileNumber": "+91 98101 11002",
    "whatsappNumber": "+91 98101 11002",
    "gender": "Female",
    "age": 22,
    "email": "test.priya.verma@example.com",
    "city": "Delhi",
    "area": "Janakpuri",
    "address": "Block C, Janakpuri, West Delhi",
    "positionApplied": "Telecaller",
    "department": "BKD Recruitment",
    "companyId": "comp-2",
    "companyName": "BKD Retail & Lifestyle Pvt Ltd",
    "qualification": "Graduate",
    "totalExperience": "1 Year",
    "relevantExperience": "1 Year",
    "currentCompany": "CallPoint Services",
    "currentSalary": 18000,
    "expectedSalary": 22000,
    "noticePeriod": "Immediate",
    "preferredLocation": "Delhi",
    "candidateSource": "Apna",
    "assignedHr": "Shivani",
    "status": "New Lead",
    "remarks": "TEST DATA - Safe to delete",
    "isActiveJoining": false,
    "createdAt": "2026-09-06T09:30:00Z",
    "lastActivityDate": "2026-09-06T09:30:00Z"
  },
  {
    "id": "TEST-2026-003",
    "fullName": "Test Rahul Kumar",
    "mobileNumber": "+91 98101 11003",
    "whatsappNumber": "+91 98101 11003",
    "gender": "Male",
    "age": 21,
    "email": "test.rahul.kumar@example.com",
    "city": "Delhi",
    "area": "Uttam Nagar",
    "address": "East Uttam Nagar, Metro Pillar 650, Delhi",
    "positionApplied": "Customer Support Executive",
    "department": "HR Recruitment",
    "companyId": "comp-1",
    "companyName": "Essential Soul Lifestyle Pvt Ltd",
    "qualification": "12th Pass",
    "totalExperience": "Fresher",
    "relevantExperience": "Fresher",
    "currentCompany": "N/A",
    "currentSalary": 0,
    "expectedSalary": 18000,
    "noticePeriod": "Immediate",
    "preferredLocation": "Delhi",
    "candidateSource": "WorkIndia",
    "assignedHr": "Priyanka",
    "status": "New Lead",
    "remarks": "TEST DATA - Safe to delete",
    "isActiveJoining": false,
    "createdAt": "2026-09-06T10:00:00Z",
    "lastActivityDate": "2026-09-06T10:00:00Z"
  },
  {
    "id": "TEST-2026-004",
    "fullName": "Test Neha Singh",
    "mobileNumber": "+91 98101 11004",
    "whatsappNumber": "+91 98101 11004",
    "gender": "Female",
    "age": 25,
    "email": "test.neha.singh@example.com",
    "city": "Gurugram",
    "area": "Cyber City",
    "address": "DLF Phase 2, Gurugram, Haryana",
    "positionApplied": "HR Executive",
    "department": "HR Recruitment",
    "companyId": "comp-1",
    "companyName": "Essential Soul Lifestyle Pvt Ltd",
    "qualification": "MBA (HR)",
    "totalExperience": "2 Years",
    "relevantExperience": "2 Years",
    "currentCompany": "Apex Staffing",
    "currentSalary": 24000,
    "expectedSalary": 30000,
    "noticePeriod": "15 Days",
    "preferredLocation": "Noida / Gurugram",
    "candidateSource": "Naukri",
    "assignedHr": "Nandani",
    "status": "Interested",
    "firstCallDate": "2026-09-06T10:15:00Z",
    "remarks": "TEST DATA - Safe to delete",
    "isActiveJoining": false,
    "createdAt": "2026-09-06T08:00:00Z",
    "lastActivityDate": "2026-09-06T10:15:00Z"
  },
  {
    "id": "TEST-2026-005",
    "fullName": "Test Aman Gupta",
    "mobileNumber": "+91 98101 11005",
    "whatsappNumber": "+91 98101 11005",
    "gender": "Male",
    "age": 23,
    "email": "test.aman.gupta@example.com",
    "city": "Delhi",
    "area": "Pitampura",
    "address": "KP Block, Pitampura, North West Delhi",
    "positionApplied": "Sales Executive",
    "department": "BKD Recruitment",
    "companyId": "comp-2",
    "companyName": "BKD Retail & Lifestyle Pvt Ltd",
    "qualification": "BBA",
    "totalExperience": "1.5 Years",
    "relevantExperience": "1.5 Years",
    "currentCompany": "Zenith Retail",
    "currentSalary": 20000,
    "expectedSalary": 26000,
    "noticePeriod": "Immediate",
    "preferredLocation": "Delhi / Noida",
    "candidateSource": "Indeed",
    "assignedHr": "Shivani",
    "status": "Connected",
    "firstCallDate": "2026-09-06T10:30:00Z",
    "remarks": "TEST DATA - Safe to delete",
    "isActiveJoining": false,
    "createdAt": "2026-09-06T08:30:00Z",
    "lastActivityDate": "2026-09-06T10:30:00Z"
  },
  {
    "id": "TEST-2026-006",
    "fullName": "Test Pooja Yadav",
    "mobileNumber": "+91 98101 11006",
    "whatsappNumber": "+91 98101 11006",
    "gender": "Female",
    "age": 22,
    "email": "test.pooja.yadav@example.com",
    "city": "Delhi",
    "area": "Rohini",
    "address": "Sector 7, Rohini, North Delhi",
    "positionApplied": "Telecaller",
    "department": "HR Recruitment",
    "companyId": "comp-1",
    "companyName": "Essential Soul Lifestyle Pvt Ltd",
    "qualification": "B.A.",
    "totalExperience": "1 Year",
    "relevantExperience": "1 Year",
    "currentCompany": "Vibrant BPO",
    "currentSalary": 16000,
    "expectedSalary": 20000,
    "noticePeriod": "Immediate",
    "preferredLocation": "Delhi",
    "candidateSource": "WhatsApp",
    "assignedHr": "Priyanka",
    "status": "Interested",
    "firstCallDate": "2026-09-06T10:45:00Z",
    "remarks": "TEST DATA - Safe to delete",
    "isActiveJoining": false,
    "createdAt": "2026-09-06T09:00:00Z",
    "lastActivityDate": "2026-09-06T10:45:00Z"
  },
  {
    "id": "TEST-2026-007",
    "fullName": "Test Rohit Sharma",
    "mobileNumber": "+91 98101 11007",
    "whatsappNumber": "+91 98101 11007",
    "gender": "Male",
    "age": 28,
    "email": "test.rohit.sharma@example.com",
    "city": "Delhi",
    "area": "Peeragarhi",
    "address": "Main Rohtak Road, Peeragarhi, Delhi",
    "positionApplied": "Team Leader",
    "department": "HR Recruitment",
    "companyId": "comp-1",
    "companyName": "Essential Soul Lifestyle Pvt Ltd",
    "qualification": "MBA",
    "totalExperience": "4 Years",
    "relevantExperience": "3 Years",
    "currentCompany": "Matrix Infoline",
    "currentSalary": 32000,
    "expectedSalary": 40000,
    "noticePeriod": "15 Days",
    "preferredLocation": "Delhi / Noida",
    "candidateSource": "Naukri",
    "assignedHr": "Nandani",
    "status": "Follow-up",
    "firstCallDate": "2026-09-05T11:00:00Z",
    "remarks": "TEST DATA - Safe to delete",
    "isActiveJoining": false,
    "createdAt": "2026-09-05T10:00:00Z",
    "lastActivityDate": "2026-09-06T09:00:00Z"
  },
  {
    "id": "TEST-2026-008",
    "fullName": "Test Simran Kaur",
    "mobileNumber": "+91 98101 11008",
    "whatsappNumber": "+91 98101 11008",
    "gender": "Female",
    "age": 23,
    "email": "test.simran.kaur@example.com",
    "city": "Delhi",
    "area": "Dwarka",
    "address": "Sector 12, Dwarka, South West Delhi",
    "positionApplied": "Telecaller",
    "department": "BKD Recruitment",
    "companyId": "comp-2",
    "companyName": "BKD Retail & Lifestyle Pvt Ltd",
    "qualification": "Graduate",
    "totalExperience": "2 Years",
    "relevantExperience": "2 Years",
    "currentCompany": "DialTech",
    "currentSalary": 18000,
    "expectedSalary": 24000,
    "noticePeriod": "Immediate",
    "preferredLocation": "Delhi",
    "candidateSource": "Meta Ads",
    "assignedHr": "Shivani",
    "status": "Follow-up",
    "firstCallDate": "2026-09-05T14:00:00Z",
    "remarks": "TEST DATA - Safe to delete",
    "isActiveJoining": false,
    "createdAt": "2026-09-05T11:00:00Z",
    "lastActivityDate": "2026-09-06T09:30:00Z"
  },
  {
    "id": "TEST-2026-009",
    "fullName": "Test Deepak Kumar",
    "mobileNumber": "+91 98101 11009",
    "whatsappNumber": "+91 98101 11009",
    "gender": "Male",
    "age": 24,
    "email": "test.deepak.kumar@example.com",
    "city": "Bahadurgarh",
    "area": "Line Par",
    "address": "Ward 4, Line Par, Bahadurgarh, Haryana",
    "positionApplied": "Back Office Executive",
    "department": "HR Recruitment",
    "companyId": "comp-1",
    "companyName": "Essential Soul Lifestyle Pvt Ltd",
    "qualification": "B.Com",
    "totalExperience": "1 Year",
    "relevantExperience": "1 Year",
    "currentCompany": "Swift Logistics",
    "currentSalary": 17000,
    "expectedSalary": 22000,
    "noticePeriod": "Immediate",
    "preferredLocation": "Delhi / Bahadurgarh",
    "candidateSource": "Apna",
    "assignedHr": "Priyanka",
    "status": "Follow-up",
    "firstCallDate": "2026-09-03T11:00:00Z",
    "remarks": "TEST DATA - Safe to delete",
    "isActiveJoining": false,
    "createdAt": "2026-09-03T09:00:00Z",
    "lastActivityDate": "2026-09-04T10:00:00Z"
  },
  {
    "id": "TEST-2026-010",
    "fullName": "Test Anjali Verma",
    "mobileNumber": "+91 98101 11010",
    "whatsappNumber": "+91 98101 11010",
    "gender": "Female",
    "age": 24,
    "email": "test.anjali.verma@example.com",
    "city": "Ghaziabad",
    "area": "Indirapuram",
    "address": "Ahinsa Khand 2, Indirapuram, Ghaziabad",
    "positionApplied": "HR Executive",
    "department": "HR Recruitment",
    "companyId": "comp-1",
    "companyName": "Essential Soul Lifestyle Pvt Ltd",
    "qualification": "MBA (HR)",
    "totalExperience": "2 Years",
    "relevantExperience": "1.5 Years",
    "currentCompany": "TalentHive",
    "currentSalary": 22000,
    "expectedSalary": 28000,
    "noticePeriod": "Immediate",
    "preferredLocation": "Noida",
    "candidateSource": "Indeed",
    "assignedHr": "Nandani",
    "status": "Interview Scheduled",
    "remarks": "TEST DATA - Safe to delete",
    "firstCallDate": "2026-09-04T10:00:00Z",
    "isActiveJoining": false,
    "createdAt": "2026-09-04T10:00:00Z",
    "lastActivityDate": "2026-09-06T09:00:00Z"
  },
  {
    "id": "TEST-2026-011",
    "fullName": "Test Mohit Singh",
    "mobileNumber": "+91 98101 11011",
    "whatsappNumber": "+91 98101 11011",
    "gender": "Male",
    "age": 25,
    "email": "test.mohit.singh@example.com",
    "city": "Delhi",
    "area": "Nangloi",
    "address": "Najafgarh Road, Nangloi, Delhi",
    "positionApplied": "Sales Executive",
    "department": "BKD Recruitment",
    "companyId": "comp-2",
    "companyName": "BKD Retail & Lifestyle Pvt Ltd",
    "qualification": "Graduate",
    "totalExperience": "2.5 Years",
    "relevantExperience": "2 Years",
    "currentCompany": "City Mart",
    "currentSalary": 22000,
    "expectedSalary": 27000,
    "noticePeriod": "Immediate",
    "preferredLocation": "Delhi",
    "candidateSource": "Walk-in",
    "assignedHr": "Shivani",
    "status": "Interview Confirmed",
    "remarks": "TEST DATA - Safe to delete",
    "firstCallDate": "2026-09-04T11:00:00Z",
    "isActiveJoining": false,
    "createdAt": "2026-09-04T11:00:00Z",
    "lastActivityDate": "2026-09-06T09:30:00Z"
  },
  {
    "id": "TEST-2026-012",
    "fullName": "Test Riya Sharma",
    "mobileNumber": "+91 98101 11012",
    "whatsappNumber": "+91 98101 11012",
    "gender": "Female",
    "age": 23,
    "email": "test.riya.sharma@example.com",
    "city": "Noida",
    "area": "Sector 18",
    "address": "Atta Market, Sector 18, Noida",
    "positionApplied": "Digital Marketing Executive",
    "department": "HR Recruitment",
    "companyId": "comp-1",
    "companyName": "Essential Soul Lifestyle Pvt Ltd",
    "qualification": "B.Tech",
    "totalExperience": "1.5 Years",
    "relevantExperience": "1.5 Years",
    "currentCompany": "PixelCraft",
    "currentSalary": 25000,
    "expectedSalary": 32000,
    "noticePeriod": "15 Days",
    "preferredLocation": "Noida",
    "candidateSource": "Referral",
    "assignedHr": "Priyanka",
    "status": "Interview Scheduled",
    "remarks": "TEST DATA - Safe to delete",
    "firstCallDate": "2026-09-05T12:00:00Z",
    "isActiveJoining": false,
    "createdAt": "2026-09-05T12:00:00Z",
    "lastActivityDate": "2026-09-06T10:00:00Z"
  },
  {
    "id": "TEST-2026-013",
    "fullName": "Test Karan Gupta",
    "mobileNumber": "+91 98101 11013",
    "whatsappNumber": "+91 98101 11013",
    "gender": "Male",
    "age": 22,
    "email": "test.karan.gupta@example.com",
    "city": "Delhi",
    "area": "Janakpuri",
    "address": "District Centre, Janakpuri, New Delhi",
    "positionApplied": "Telecaller",
    "department": "BKD Recruitment",
    "companyId": "comp-2",
    "companyName": "BKD Retail & Lifestyle Pvt Ltd",
    "qualification": "12th Pass",
    "totalExperience": "1 Year",
    "relevantExperience": "1 Year",
    "currentCompany": "ConnectPlus",
    "currentSalary": 16000,
    "expectedSalary": 20000,
    "noticePeriod": "Immediate",
    "preferredLocation": "Delhi",
    "candidateSource": "Apna",
    "assignedHr": "Shivani",
    "status": "Interview Confirmed",
    "remarks": "TEST DATA - Safe to delete",
    "firstCallDate": "2026-09-05T14:00:00Z",
    "isActiveJoining": false,
    "createdAt": "2026-09-05T14:00:00Z",
    "lastActivityDate": "2026-09-06T10:15:00Z"
  },
  {
    "id": "TEST-2026-014",
    "fullName": "Test Sneha Kapoor",
    "mobileNumber": "+91 98101 11014",
    "whatsappNumber": "+91 98101 11014",
    "gender": "Female",
    "age": 26,
    "email": "test.sneha.kapoor@example.com",
    "city": "Delhi",
    "area": "Pitampura",
    "address": "Netaji Subhash Place, Pitampura, Delhi",
    "positionApplied": "Sales Executive",
    "department": "HR Recruitment",
    "companyId": "comp-1",
    "companyName": "Essential Soul Lifestyle Pvt Ltd",
    "qualification": "B.Com",
    "totalExperience": "3 Years",
    "relevantExperience": "2.5 Years",
    "currentCompany": "Prime Trends",
    "currentSalary": 26000,
    "expectedSalary": 32000,
    "noticePeriod": "Immediate",
    "preferredLocation": "Delhi / Noida",
    "candidateSource": "Naukri",
    "assignedHr": "Nandani",
    "status": "Interview Conducted",
    "remarks": "TEST DATA - Safe to delete",
    "firstCallDate": "2026-09-04T09:00:00Z",
    "isActiveJoining": false,
    "createdAt": "2026-09-04T09:00:00Z",
    "lastActivityDate": "2026-09-06T11:00:00Z"
  },
  {
    "id": "TEST-2026-015",
    "fullName": "Test Vishal Yadav",
    "mobileNumber": "+91 98101 11015",
    "whatsappNumber": "+91 98101 11015",
    "gender": "Male",
    "age": 23,
    "email": "test.vishal.yadav@example.com",
    "city": "Delhi",
    "area": "Uttam Nagar",
    "address": "Near Metro Station, Uttam Nagar, Delhi",
    "positionApplied": "Telecaller",
    "department": "BKD Recruitment",
    "companyId": "comp-2",
    "companyName": "BKD Retail & Lifestyle Pvt Ltd",
    "qualification": "B.A.",
    "totalExperience": "1.5 Years",
    "relevantExperience": "1.5 Years",
    "currentCompany": "TeleMax Solutions",
    "currentSalary": 17000,
    "expectedSalary": 21000,
    "noticePeriod": "Immediate",
    "preferredLocation": "Delhi",
    "candidateSource": "WorkIndia",
    "assignedHr": "Shivani",
    "status": "Interview Conducted",
    "remarks": "TEST DATA - Safe to delete",
    "firstCallDate": "2026-09-04T12:00:00Z",
    "isActiveJoining": false,
    "createdAt": "2026-09-04T12:00:00Z",
    "lastActivityDate": "2026-09-06T11:45:00Z"
  },
  {
    "id": "TEST-2026-016",
    "fullName": "Test Komal Singh",
    "mobileNumber": "+91 98101 11016",
    "whatsappNumber": "+91 98101 11016",
    "gender": "Female",
    "age": 25,
    "email": "test.komal.singh@example.com",
    "city": "Noida",
    "area": "Sector 62",
    "address": "Tower 3, Sector 62, Noida",
    "positionApplied": "HR Executive",
    "department": "HR Recruitment",
    "companyId": "comp-1",
    "companyName": "Essential Soul Lifestyle Pvt Ltd",
    "qualification": "MBA (HR)",
    "totalExperience": "2 Years",
    "relevantExperience": "2 Years",
    "currentCompany": "ProPeople",
    "currentSalary": 24000,
    "expectedSalary": 30000,
    "salaryOffered": 28000,
    "selectionDate": "2026-09-06",
    "reportingManager": "Nandani Sharma (HR Head)",
    "officeLocation": "ITHUM Tower, Block A, Sector 62, Noida",
    "noticePeriod": "Immediate",
    "preferredLocation": "Noida",
    "candidateSource": "Indeed",
    "assignedHr": "Nandani",
    "status": "Selected",
    "remarks": "TEST DATA - Safe to delete",
    "firstCallDate": "2026-09-03T09:00:00Z",
    "isActiveJoining": false,
    "createdAt": "2026-09-03T09:00:00Z",
    "lastActivityDate": "2026-09-06T12:00:00Z"
  },
  {
    "id": "TEST-2026-017",
    "fullName": "Test Akash Verma",
    "mobileNumber": "+91 98101 11017",
    "whatsappNumber": "+91 98101 11017",
    "gender": "Male",
    "age": 24,
    "email": "test.akash.verma@example.com",
    "city": "Delhi",
    "area": "Dwarka",
    "address": "Sector 10, Dwarka, Delhi",
    "positionApplied": "Sales Executive",
    "department": "BKD Recruitment",
    "companyId": "comp-2",
    "companyName": "BKD Retail & Lifestyle Pvt Ltd",
    "qualification": "Graduate",
    "totalExperience": "2 Years",
    "relevantExperience": "2 Years",
    "currentCompany": "Lifestyle Hub",
    "currentSalary": 21000,
    "expectedSalary": 26000,
    "salaryOffered": 25000,
    "selectionDate": "2026-09-06",
    "reportingManager": "Rajesh Khanna (Team Leader)",
    "officeLocation": "B-12, Sector 63, Noida",
    "noticePeriod": "Immediate",
    "preferredLocation": "Delhi / Noida",
    "candidateSource": "Meta Ads",
    "assignedHr": "Priyanka",
    "status": "Selected",
    "remarks": "TEST DATA - Safe to delete",
    "firstCallDate": "2026-09-03T10:00:00Z",
    "isActiveJoining": false,
    "createdAt": "2026-09-03T10:00:00Z",
    "lastActivityDate": "2026-09-06T12:30:00Z"
  },
  {
    "id": "TEST-2026-018",
    "fullName": "Test Nisha Gupta",
    "mobileNumber": "+91 98101 11018",
    "whatsappNumber": "+91 98101 11018",
    "gender": "Female",
    "age": 22,
    "email": "test.nisha.gupta@example.com",
    "city": "Delhi",
    "area": "Rohini",
    "address": "Sector 11, Rohini, Delhi",
    "positionApplied": "Telecaller",
    "department": "BKD Recruitment",
    "companyId": "comp-2",
    "companyName": "BKD Retail & Lifestyle Pvt Ltd",
    "qualification": "12th Pass",
    "totalExperience": "1 Year",
    "relevantExperience": "1 Year",
    "currentCompany": "QuickCall",
    "currentSalary": 16000,
    "expectedSalary": 20000,
    "salaryOffered": 20000,
    "selectionDate": "2026-09-02",
    "joiningDate": "2026-09-06",
    "actualJoinedDate": "2026-09-06",
    "reportingTime": "09:30 AM",
    "reportingManager": "Pooja Verma",
    "officeLocation": "B-12, Sector 63, Noida",
    "joiningStatus": "Joined",
    "isActiveJoining": false,
    "noticePeriod": "Immediate",
    "preferredLocation": "Delhi",
    "candidateSource": "Apna",
    "assignedHr": "Shivani",
    "status": "Joined",
    "remarks": "TEST DATA - Safe to delete",
    "firstCallDate": "2026-09-01T09:00:00Z",
    "createdAt": "2026-09-01T09:00:00Z",
    "lastActivityDate": "2026-09-06T09:30:00Z"
  },
  {
    "id": "TEST-2026-019",
    "fullName": "Test Manish Kumar",
    "mobileNumber": "+91 98101 11019",
    "whatsappNumber": "+91 98101 11019",
    "gender": "Male",
    "age": 26,
    "email": "test.manish.kumar@example.com",
    "city": "Ghaziabad",
    "area": "Vaishali",
    "address": "Sector 4, Vaishali, Ghaziabad",
    "positionApplied": "Back Office Executive",
    "department": "HR Recruitment",
    "companyId": "comp-1",
    "companyName": "Essential Soul Lifestyle Pvt Ltd",
    "qualification": "Graduate",
    "totalExperience": "2.5 Years",
    "relevantExperience": "2 Years",
    "currentCompany": "Alpha Ops",
    "currentSalary": 20000,
    "expectedSalary": 25000,
    "salaryOffered": 24000,
    "selectionDate": "2026-08-25",
    "joiningDate": "2026-08-30",
    "actualJoinedDate": "2026-08-30",
    "activeJoinedDate": "2026-09-06",
    "isActiveJoining": true,
    "joiningStatus": "Joined",
    "reportingManager": "Aditya Mathur",
    "officeLocation": "Plot A-40, Sector 62, Noida",
    "noticePeriod": "Immediate",
    "preferredLocation": "Noida / Ghaziabad",
    "candidateSource": "Naukri",
    "assignedHr": "Nandani",
    "status": "Active Joining",
    "remarks": "TEST DATA - Safe to delete",
    "firstCallDate": "2026-08-20T10:00:00Z",
    "createdAt": "2026-08-20T10:00:00Z",
    "lastActivityDate": "2026-09-06T10:00:00Z"
  },
  {
    "id": "TEST-2026-020",
    "fullName": "Test Sakshi Sharma",
    "mobileNumber": "+91 98101 11020",
    "whatsappNumber": "+91 98101 11020",
    "gender": "Female",
    "age": 23,
    "email": "test.sakshi.sharma@example.com",
    "city": "Delhi",
    "area": "Peeragarhi",
    "address": "Udyog Nagar Metro, Peeragarhi, Delhi",
    "positionApplied": "Customer Support Executive",
    "department": "HR Recruitment",
    "companyId": "comp-1",
    "companyName": "Essential Soul Lifestyle Pvt Ltd",
    "qualification": "Graduate",
    "totalExperience": "1 Year",
    "relevantExperience": "1 Year",
    "currentCompany": "ZenDesk Care",
    "currentSalary": 17000,
    "expectedSalary": 21000,
    "noticePeriod": "Immediate",
    "preferredLocation": "Delhi",
    "candidateSource": "WorkIndia",
    "assignedHr": "Priyanka",
    "status": "No Show",
    "remarks": "TEST DATA - Safe to delete",
    "firstCallDate": "2026-09-02T10:00:00Z",
    "isActiveJoining": false,
    "createdAt": "2026-09-02T10:00:00Z",
    "lastActivityDate": "2026-09-05T15:00:00Z"
  }
];

export const INITIAL_FOLLOW_UPS: FollowUpRecord[] = [
  {
    "id": "test-fu-001",
    "candidateId": "TEST-2026-007",
    "candidateName": "Test Rohit Sharma",
    "candidateMobile": "+91 98101 11007",
    "position": "Team Leader",
    "hrExecutive": "Nandani",
    "followUpDate": "2026-09-06",
    "followUpTime": "11:30",
    "followUpMode": "Call",
    "candidateResponse": "Requested afternoon call after 2 PM to finalize interview slot.",
    "notes": "Candidate asked to call back in afternoon after 2 PM to finalize interview slot.",
    "nextFollowUpDate": "2026-09-06",
    "nextFollowUpTime": "14:30",
    "resultingStatus": "Follow-up",
    "isCompleted": false,
    "createdAt": "2026-09-05T11:00:00Z"
  },
  {
    "id": "test-fu-002",
    "candidateId": "TEST-2026-008",
    "candidateName": "Test Simran Kaur",
    "candidateMobile": "+91 98101 11008",
    "position": "Telecaller",
    "hrExecutive": "Shivani",
    "followUpDate": "2026-09-06",
    "followUpTime": "14:00",
    "followUpMode": "Call",
    "candidateResponse": "Interested in Telecaller role, needs salary confirmation before scheduling.",
    "notes": "Interested in Telecaller role, needs salary confirmation before scheduling.",
    "nextFollowUpDate": "2026-09-06",
    "nextFollowUpTime": "16:00",
    "resultingStatus": "Follow-up",
    "isCompleted": false,
    "createdAt": "2026-09-05T14:00:00Z"
  },
  {
    "id": "test-fu-003",
    "candidateId": "TEST-2026-009",
    "candidateName": "Test Deepak Kumar",
    "candidateMobile": "+91 98101 11009",
    "position": "Back Office Executive",
    "hrExecutive": "Priyanka",
    "followUpDate": "2026-09-04",
    "followUpTime": "10:00",
    "followUpMode": "Call",
    "candidateResponse": "Phone was busy on first attempt; reschedule touchpoint.",
    "notes": "Phone was busy on first attempt; reschedule touchpoint.",
    "nextFollowUpDate": "2026-09-06",
    "nextFollowUpTime": "11:00",
    "resultingStatus": "Follow-up",
    "isCompleted": false,
    "createdAt": "2026-09-03T11:00:00Z"
  },
  {
    "id": "test-fu-004",
    "candidateId": "TEST-2026-008",
    "candidateName": "Test Simran Kaur",
    "candidateMobile": "+91 98101 11008",
    "position": "Telecaller",
    "hrExecutive": "Shivani",
    "followUpDate": "2026-09-08",
    "followUpTime": "15:00",
    "followUpMode": "WhatsApp",
    "candidateResponse": "Scheduled upcoming WhatsApp check-in for document submission.",
    "notes": "Scheduled upcoming WhatsApp check-in for document submission.",
    "nextFollowUpDate": "2026-09-08",
    "nextFollowUpTime": "15:00",
    "resultingStatus": "Follow-up",
    "isCompleted": false,
    "createdAt": "2026-09-06T09:00:00Z"
  }
];

export const INITIAL_INTERVIEWS: InterviewRecord[] = [
  {
    "id": "test-int-001",
    "candidateId": "TEST-2026-010",
    "candidateName": "Test Anjali Verma",
    "candidateMobile": "+91 98101 11010",
    "position": "HR Executive",
    "department": "HR Recruitment",
    "hrExecutive": "Nandani",
    "interviewer": "Vikram Singh",
    "interviewDate": "2026-09-06",
    "interviewTime": "11:00",
    "interviewMode": "Office Interview",
    "interviewLocation": "Plot A-40, ITHUM Tower, Sector 62, Noida",
    "attendanceStatus": "Scheduled",
    "reminderSent": true,
    "remarks": "Office interview at Sector 62, Noida. Candidate confirmed arrival.",
    "createdAt": "2026-09-04T10:00:00Z"
  },
  {
    "id": "test-int-002",
    "candidateId": "TEST-2026-011",
    "candidateName": "Test Mohit Singh",
    "candidateMobile": "+91 98101 11011",
    "position": "Sales Executive",
    "department": "BKD Recruitment",
    "hrExecutive": "Shivani",
    "interviewer": "Rajesh Khanna",
    "interviewDate": "2026-09-06",
    "interviewTime": "12:30",
    "interviewMode": "Office Interview",
    "interviewLocation": "B-12, Sector 63, Noida",
    "attendanceStatus": "Confirmed",
    "reminderSent": true,
    "remarks": "In-person interview at B-12 Sector 63, Noida. Candidate re-confirmed on morning call.",
    "createdAt": "2026-09-04T11:00:00Z"
  },
  {
    "id": "test-int-003",
    "candidateId": "TEST-2026-012",
    "candidateName": "Test Riya Sharma",
    "candidateMobile": "+91 98101 11012",
    "position": "Digital Marketing Executive",
    "department": "HR Recruitment",
    "hrExecutive": "Priyanka",
    "interviewer": "Aditya Mathur",
    "interviewDate": "2026-09-08",
    "interviewTime": "14:00",
    "interviewMode": "Video Interview",
    "interviewLocation": "Google Meet",
    "attendanceStatus": "Scheduled",
    "reminderSent": true,
    "remarks": "Video interview scheduled via Google Meet.",
    "createdAt": "2026-09-05T12:00:00Z"
  },
  {
    "id": "test-int-004",
    "candidateId": "TEST-2026-013",
    "candidateName": "Test Karan Gupta",
    "candidateMobile": "+91 98101 11013",
    "position": "Telecaller",
    "department": "BKD Recruitment",
    "hrExecutive": "Shivani",
    "interviewer": "Pooja Verma",
    "interviewDate": "2026-09-06",
    "interviewTime": "15:00",
    "interviewMode": "Phone Interview",
    "interviewLocation": "Telephonic Round",
    "attendanceStatus": "Confirmed",
    "reminderSent": true,
    "remarks": "Telephonic communication and vocal screening interview.",
    "createdAt": "2026-09-05T14:00:00Z"
  },
  {
    "id": "test-int-005",
    "candidateId": "TEST-2026-014",
    "candidateName": "Test Sneha Kapoor",
    "candidateMobile": "+91 98101 11014",
    "position": "Sales Executive",
    "department": "HR Recruitment",
    "hrExecutive": "Nandani",
    "interviewer": "Vikram Singh",
    "interviewDate": "2026-09-06",
    "interviewTime": "10:30",
    "interviewMode": "Office Interview",
    "interviewLocation": "Plot A-40, ITHUM Tower, Sector 62, Noida",
    "attendanceStatus": "Conducted",
    "reminderSent": true,
    "evaluation": {
      "communication": 4,
      "confidence": 4,
      "experience": 3,
      "jobKnowledge": 4,
      "stability": 4,
      "salaryFit": 4,
      "attitude": 5,
      "overallSuitability": 4,
      "averageRating": 4.0,
      "finalResult": "Selected",
      "interviewerRemarks": "Strong candidate with clear product pitch presentation. Recommended for offer release.",
      "evaluatedAt": "2026-09-06T11:00:00Z"
    },
    "remarks": "Interview completed successfully; candidate demonstrated great retail and floor sales aptitude.",
    "createdAt": "2026-09-04T09:00:00Z"
  },
  {
    "id": "test-int-006",
    "candidateId": "TEST-2026-015",
    "candidateName": "Test Vishal Yadav",
    "candidateMobile": "+91 98101 11015",
    "position": "Telecaller",
    "department": "BKD Recruitment",
    "hrExecutive": "Shivani",
    "interviewer": "Rahul Deshmukh",
    "interviewDate": "2026-09-06",
    "interviewTime": "11:30",
    "interviewMode": "Office Interview",
    "interviewLocation": "B-12, Sector 63, Noida",
    "attendanceStatus": "Conducted",
    "reminderSent": true,
    "evaluation": {
      "communication": 4,
      "confidence": 3,
      "experience": 3,
      "jobKnowledge": 3,
      "stability": 3,
      "salaryFit": 4,
      "attitude": 4,
      "overallSuitability": 3.5,
      "averageRating": 3.5,
      "finalResult": "Salary Discussion",
      "interviewerRemarks": "Good dialect and vocal clarity. Fits budget, slight negotiation needed.",
      "evaluatedAt": "2026-09-06T11:45:00Z"
    },
    "remarks": "Conducted assessment. Good fit for voice process.",
    "createdAt": "2026-09-04T12:00:00Z"
  },
  {
    "id": "test-int-007",
    "candidateId": "TEST-2026-016",
    "candidateName": "Test Komal Singh",
    "candidateMobile": "+91 98101 11016",
    "position": "HR Executive",
    "department": "HR Recruitment",
    "hrExecutive": "Nandani",
    "interviewer": "Vikram Singh",
    "interviewDate": "2026-09-05",
    "interviewTime": "14:00",
    "interviewMode": "Office Interview",
    "interviewLocation": "Plot A-40, ITHUM Tower, Sector 62, Noida",
    "attendanceStatus": "Conducted",
    "reminderSent": true,
    "evaluation": {
      "communication": 5,
      "confidence": 4,
      "experience": 4,
      "jobKnowledge": 4,
      "stability": 4,
      "salaryFit": 4,
      "attitude": 5,
      "overallSuitability": 4.5,
      "averageRating": 4.2,
      "finalResult": "Selected",
      "interviewerRemarks": "Excellent HR lifecycle domain knowledge. Selected for offer.",
      "evaluatedAt": "2026-09-05T15:00:00Z"
    },
    "remarks": "Selected candidate.",
    "createdAt": "2026-09-03T09:00:00Z"
  },
  {
    "id": "test-int-008",
    "candidateId": "TEST-2026-017",
    "candidateName": "Test Akash Verma",
    "candidateMobile": "+91 98101 11017",
    "position": "Sales Executive",
    "department": "BKD Recruitment",
    "hrExecutive": "Priyanka",
    "interviewer": "Rajesh Khanna",
    "interviewDate": "2026-09-05",
    "interviewTime": "16:00",
    "interviewMode": "Office Interview",
    "interviewLocation": "B-12, Sector 63, Noida",
    "attendanceStatus": "Conducted",
    "reminderSent": true,
    "evaluation": {
      "communication": 4,
      "confidence": 4,
      "experience": 4,
      "jobKnowledge": 4,
      "stability": 4,
      "salaryFit": 4,
      "attitude": 4,
      "overallSuitability": 4.0,
      "averageRating": 4.0,
      "finalResult": "Selected",
      "interviewerRemarks": "Strong retail sales flair, selected for BKD team.",
      "evaluatedAt": "2026-09-05T17:00:00Z"
    },
    "remarks": "Selected candidate.",
    "createdAt": "2026-09-03T10:00:00Z"
  },
  {
    "id": "test-int-009",
    "candidateId": "TEST-2026-020",
    "candidateName": "Test Sakshi Sharma",
    "candidateMobile": "+91 98101 11020",
    "position": "Customer Support Executive",
    "department": "HR Recruitment",
    "hrExecutive": "Priyanka",
    "interviewer": "Vikram Singh",
    "interviewDate": "2026-09-05",
    "interviewTime": "14:30",
    "interviewMode": "Office Interview",
    "interviewLocation": "Plot A-40, ITHUM Tower, Sector 62, Noida",
    "attendanceStatus": "No Show",
    "reminderSent": true,
    "remarks": "Candidate did not attend scheduled interview; phone switched off on follow-up.",
    "createdAt": "2026-09-02T10:00:00Z"
  }
];

export const INITIAL_JOB_OPENINGS: JobOpening[] = [
  {
    id: 'job-1',
    jobTitle: 'Sales Executive',
    department: 'HR Recruitment',
    vacancies: 10,
    filledPositions: 4,
    salaryRange: '₹20,000 - ₹28,000 + Incentives',
    jobLocation: 'Sector 62, Noida',
    experience: '1-3 Years',
    hrResponsible: 'Nandani',
    hiringDeadline: '2026-09-30',
    status: 'Urgent',
  },
  {
    id: 'job-2',
    jobTitle: 'Telecaller',
    department: 'BKD Recruitment',
    vacancies: 15,
    filledPositions: 8,
    salaryRange: '₹16,000 - ₹22,000 + Incentives',
    jobLocation: 'Sector 62, Noida',
    experience: '0-2 Years',
    hrResponsible: 'Shivani',
    hiringDeadline: '2026-09-25',
    status: 'Open',
  },
  {
    id: 'job-3',
    jobTitle: 'HR Executive',
    department: 'HR Recruitment',
    vacancies: 2,
    filledPositions: 1,
    salaryRange: '₹22,000 - ₹28,000',
    jobLocation: 'Sector 62, Noida',
    experience: '1-2 Years',
    hrResponsible: 'Nandani',
    hiringDeadline: '2026-09-20',
    status: 'Open',
  },
  {
    id: 'job-4',
    jobTitle: 'Team Leader',
    department: 'BKD Recruitment',
    vacancies: 3,
    filledPositions: 1,
    salaryRange: '₹32,000 - ₹40,000',
    jobLocation: 'Sector 62, Noida',
    experience: '3-5 Years',
    hrResponsible: 'Shivani',
    hiringDeadline: '2026-09-18',
    status: 'Urgent',
  },
  {
    id: 'job-5',
    jobTitle: 'Digital Marketing Executive',
    department: 'HR Recruitment',
    vacancies: 2,
    filledPositions: 0,
    salaryRange: '₹25,000 - ₹35,000',
    jobLocation: 'Sector 62, Noida',
    experience: '2-4 Years',
    hrResponsible: 'Nandani',
    hiringDeadline: '2026-09-30',
    status: 'Open',
  },
  {
    id: 'job-6',
    jobTitle: 'Back Office Executive',
    department: 'HR Recruitment',
    vacancies: 4,
    filledPositions: 2,
    salaryRange: '₹18,000 - ₹24,000',
    jobLocation: 'Sector 62, Noida',
    experience: '1-2 Years',
    hrResponsible: 'Nandani',
    hiringDeadline: '2026-09-22',
    status: 'Open',
  },
];

export const INITIAL_SOURCE_AD_SPENDS: SourceAdSpend[] = [
  { source: 'Meta Ads', adSpend: 35000 },
  { source: 'Facebook', adSpend: 15000 },
  { source: 'Instagram', adSpend: 18000 },
  { source: 'WhatsApp', adSpend: 5000 },
  { source: 'Indeed', adSpend: 22000 },
  { source: 'Naukri', adSpend: 28000 },
  { source: 'Apna', adSpend: 16000 },
  { source: 'WorkIndia', adSpend: 12000 },
  { source: 'Referral', adSpend: 4000 },
  { source: 'Walk-in', adSpend: 0 },
  { source: 'Data Vendor', adSpend: 15000 },
  { source: 'Existing Database', adSpend: 0 },
  { source: 'Other', adSpend: 2000 },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [];

export const DEFAULT_ROLE_PERMISSIONS: RolePermissionsMap = {
  'Super Admin': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'companies',
    'users',
    'departments',
    'targets',
    'permissions',
    'import-export',
    'reports',
    'templates',
    'audit',
    'database',
  ],
  'Director / Management': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'companies',
    'users',
    'departments',
    'targets',
    'permissions',
    'import-export',
    'reports',
    'templates',
    'audit',
    'database',
  ],
  'HR Head': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'companies',
    'departments',
    'targets',
    'permissions',
    'import-export',
    'reports',
    'templates',
    'audit',
    'database',
  ],
  'Team Leader': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'targets',
    'import-export',
    'reports',
    'templates',
  ],
  'HR Executive': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'import-export',
    'templates',
  ],
  'Recruiter': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'import-export',
    'templates',
  ],
  'Interviewer': [
    'dashboard',
    'interviews',
    'candidates',
    'jobs',
    'terms-conditions',
  ],
};

export const INITIAL_TERMS_CLAUSES: TermsClause[] = [
  {
    id: 'tc-1',
    clauseNumber: '1.0',
    category: 'Probation & Confirmation',
    title: 'Probationary Period & Evaluation',
    content: 'The employee shall be on probation for an initial period of 90 (ninety) calendar days from the Date of Joining. During this period, performance, discipline, adherence to operational calling targets, and team alignment will be reviewed on a continuous monthly basis. The company reserves the absolute right to extend the probation period or dispense with services if benchmark standards are not satisfactorily met.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Aditya Mathur (Director)',
  },
  {
    id: 'tc-2',
    clauseNumber: '2.0',
    category: 'Working Hours & Attendance',
    title: 'Operating Hours, Shifts & Biometric Attendance',
    content: 'Standard operational working hours are Monday through Saturday from 9:30 AM to 6:30 PM with a designated 45-minute lunch break. Punctuality is strictly enforced; daily attendance must be marked via the biometric sensor or registered mobile ATS application. Three unexcused tardy arrivals exceeding 15 minutes within a calendar month shall result in the forfeiture of half a day of casual leave.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Nandani (HR Head)',
  },
  {
    id: 'tc-3',
    clauseNumber: '3.0',
    category: 'Compensation & Incentives',
    title: 'Payroll Disbursement Cycle & Target-Linked Incentives',
    content: 'Salary is disbursed monthly on or before the 7th calendar day following the payroll cycle directly into the registered bank account. Remuneration is subject to all statutory deductions including TDS, Employee Provident Fund (EPF), Employee State Insurance (ESIC), and Professional Tax where applicable. Variable performance incentives are calculated strictly based on verified active candidate joinings sustaining beyond the 7-day threshold.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Aditya Mathur (Director)',
  },
  {
    id: 'tc-4',
    clauseNumber: '4.0',
    category: 'Code of Conduct',
    title: 'Professional Integrity, Workplace Decorum & POSH Policy',
    content: 'The employee agrees to observe the highest standards of professional conduct, truthfulness, and decorum at all times. The company enforces strict zero-tolerance towards sexual harassment, verbal abuse, hate speech, insubordination, or discrimination in strict accordance with the Prevention of Sexual Harassment of Women at Workplace (POSH) Act 2013.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Nandani (HR Head)',
  },
  {
    id: 'tc-5',
    clauseNumber: '5.0',
    category: 'Confidentiality & NDA',
    title: 'Proprietary Candidate Databases, Client Data & Non-Disclosure',
    content: 'The employee shall maintain absolute confidentiality regarding candidate resumes, mobile numbers, WhatsApp transcripts, client contracts, commercial recruitment fee structures, and internal candidate pipelining metrics. All such materials remain exclusive trade secrets of Essential Soul Lifestyle Pvt Ltd and must never be extracted, photographed, forwarded, or utilized outside company business.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Aditya Mathur (Director)',
  },
  {
    id: 'tc-6',
    clauseNumber: '6.0',
    category: 'Leave & Time Off',
    title: 'Leave Accrual & Prior Approval Guidelines',
    content: 'Subsequent to successful confirmation post-probation, the employee is entitled to 18 (eighteen) days of paid leave annually, accrued at 1.5 days per completed calendar month. Any planned absence must be submitted in the recruitment portal at least 48 hours in advance and sanctioned in writing by the Team Leader or Department Head. Unsanctioned absence exceeding 3 consecutive days will be considered job abandonment.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Nandani (HR Head)',
  },
  {
    id: 'tc-7',
    clauseNumber: '7.0',
    category: 'Termination & Notice',
    title: 'Notice Period, Separation Formalities & Full and Final Settlement',
    content: 'During the probationary period, either party may terminate this employment contract by providing 15 (fifteen) calendar days notice in writing or gross salary in lieu thereof. Upon confirmation, the notice period shall be 30 (thirty) calendar days. The employee must complete a formal handover of all pending candidate pipeline leads, client files, and company equipment prior to release of Full & Final (F&F) settlement.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Aditya Mathur (Director)',
  },
  {
    id: 'tc-8',
    clauseNumber: '8.0',
    category: 'Onboarding Documents',
    title: 'Credential Verification & Mandatory Submission Checklist',
    content: 'This offer of employment is contingent upon prompt receipt and background verification of mandatory documents: self-attested copies of Aadhaar Card, PAN Card, Graduation/Post-Graduation Degree & Final Marksheet, Relieving/Experience Letter from prior employer, last 3 months salary slips/bank statements, and 3 passport-sized color photographs.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Shivani (HR Executive)',
  },
];

export const INITIAL_OFFER_LETTERS: OfferLetter[] = [
  {
    id: 'OFR-2026-001',
    candidateId: 'ESL-2026-022',
    candidateName: 'Megha Saxena',
    candidateEmail: 'megha.saxena@gmail.com',
    candidatePhone: '+91 98201 11022',
    candidateAddress: 'Flat 402, Lotus Greens, Sector 62, Noida, UP',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    companyLegalName: 'Essential Soul Lifestyle Private Limited',
    companyAddress: 'Plot A-40, ITHUM Tower, Block A, Sector 62, Noida, Uttar Pradesh, 201309',
    companyCin: 'U74999UP2022PTC168921',
    companyGstin: '09AAECE1234F1Z5',
    department: 'HR Recruitment',
    designation: 'Customer Support Executive',
    employmentType: 'Full-Time',
    workLocation: 'Sector 62, Noida',
    location: 'Sector 62, Noida',
    reportingManager: 'Aditya Mathur (Director)',
    offerDate: '2026-09-02',
    joiningDate: '2026-09-08',
    validityDate: '2026-09-06',
    annualCtc: 288000,
    monthlyGross: 24000,
    basicSalary: 12000,
    hra: 6000,
    specialAllowance: 6000,
    performanceIncentive: 3000,
    monthlyInHand: 22200,
    probationMonths: 3,
    noticePeriodDays: 30,
    status: 'Accepted',
    authorizedSignatoryName: 'Aditya Mathur',
    authorizedSignatoryTitle: 'Director',
    selectedClauseIds: ['tc-1', 'tc-2', 'tc-3', 'tc-4', 'tc-5', 'tc-6', 'tc-7', 'tc-8'],
    createdAt: '2026-09-02T11:00:00Z',
    updatedAt: '2026-09-02T11:00:00Z',
  },
  {
    id: 'OFR-2026-002',
    candidateId: 'ESL-2026-023',
    candidateName: 'Aman Gupta',
    candidateEmail: 'aman.gupta@gmail.com',
    candidatePhone: '+91 98201 11023',
    candidateAddress: 'House 128, Sector 55, Noida, UP',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    companyLegalName: 'Essential Soul Lifestyle Private Limited',
    companyAddress: 'Plot A-40, ITHUM Tower, Block A, Sector 62, Noida, Uttar Pradesh, 201309',
    department: 'HR Recruitment',
    designation: 'Back Office Executive',
    employmentType: 'Full-Time',
    workLocation: 'Sector 62, Noida',
    reportingManager: 'Vikram Singh (Operations)',
    offerDate: '2026-08-28',
    joiningDate: '2026-09-01',
    validityDate: '2026-08-31',
    annualCtc: 240000,
    monthlyGross: 20000,
    basicSalary: 10000,
    hra: 5000,
    specialAllowance: 5000,
    monthlyInHand: 18500,
    probationMonths: 3,
    noticePeriodDays: 30,
    status: 'Joined',
    authorizedSignatoryName: 'Aditya Mathur',
    authorizedSignatoryTitle: 'Director',
    selectedClauseIds: ['tc-1', 'tc-2', 'tc-3', 'tc-4', 'tc-5', 'tc-7', 'tc-8'],
    createdAt: '2026-08-28T10:00:00Z',
    updatedAt: '2026-08-28T10:00:00Z',
  },
];
